# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stockdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('underlying_symbol', models.CharField(default=b'', max_length=5)),
                ('quote_date', models.DateTimeField(blank=True, null=True)),
                ('open', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('close', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('trade_volume', models.IntegerField(blank=True, default=0, null=True)),
                ('vwap', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('best_bid_1545', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('best_ask_1545', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('best_bid_eod', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('best_ask_eod', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
            ],
            options={
                'db_table': '"stockdata"',
                'managed': True,
            },
        ),
    ]
