""" A django model generated with django-csvimport csvinspect
    which used OKN messytables to guess data types - may need some manual tweaks!
"""
from django.db import models


class Stockdata(models.Model):
    ''' Autogenerated model file csvimport Thu Nov  2 18:31:34 2017 '''

    underlying_symbol = models.CharField(default='', max_length=5, null=False, blank=False)
    quote_date = models.DateTimeField(null=True, blank=True)
    open = models.DecimalField(default=0, null=True, max_digits=6, decimal_places=3, blank=True)
    high = models.DecimalField(default=0, null=True, max_digits=6, decimal_places=3, blank=True)
    low = models.DecimalField(default=0, null=True, max_digits=6, decimal_places=3, blank=True)
    close = models.DecimalField(default=0, null=True, max_digits=6, decimal_places=3, blank=True)
    trade_volume = models.IntegerField(default=0, null=True, blank=True)
    vwap = models.DecimalField(default=0, null=True, max_digits=6, decimal_places=3, blank=True)
    best_bid_1545 = models.DecimalField(default=0, null=True, max_digits=6, decimal_places=3, blank=True)
    best_ask_1545 = models.DecimalField(default=0, null=True, max_digits=6, decimal_places=3, blank=True)
    best_bid_eod = models.DecimalField(default=0, null=True, max_digits=6, decimal_places=3, blank=True)
    best_ask_eod = models.DecimalField(default=0, null=True, max_digits=6, decimal_places=3, blank=True)

    class Meta:
        managed = True
        db_table = u'"stockdata"'
